courseSite/urls.py
from django.contrib import admin
from django.urls import path,re_path
from . import views
from course_work.views import CourseView,NewCourseView,\
    AcceptRequestView,DeleteRequestView,ChooseYourPerformerView,\
    CompleteCourseView,upload_file,download,RdyCourseView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.login_user),
    path('register/', views.register_user, name='register'),
    path('', views.main_page,name ='main'),
    path('course/', CourseView.as_view(), name ='course'),
    path('course/new', NewCourseView.as_view(), name='new_course'),
    path('course/accept/<int:pk>', AcceptRequestView.as_view(), name='accept_request'),
    path('course/delete/<int:pk>',DeleteRequestView.as_view(), name='delete_request'),
    path('course/choose_performer/<int:pk>/<int:performer_id>',ChooseYourPerformerView.as_view(), name ='choose_performer'),
    path('complete_course',CompleteCourseView.as_view(), name ='complete_course'),
    path('rdy_course',RdyCourseView.as_view(), name ='rdy_course'),
    path('upload_file/<int:pk>',upload_file,name='upload_file'),
    re_path('download/(?P<path>.*)$',download,name ='download'),
]
urlpatterns+=static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

course_work/models.py
from django.db import models
from django.contrib.auth.models import User
from main.models import Profile
from django.forms.models import modelform_factory

class Course_Request(models.Model):
    owner_user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    topic = models.TextField(max_length=60)
    description = models.TextField(max_length=600,default='')
    university = models.TextField(max_length=40,blank=True)
    teacher = models.TextField(max_length=40,blank=True)
    min_price = models.IntegerField(default=10)
    max_price = models.IntegerField(default=100)
    on_processing = models.BooleanField(default=False)
    

class Request_offers(models.Model):
    course_request = models.ForeignKey(Course_Request, on_delete=models.CASCADE)
    owner_performer = models.ForeignKey(Profile, on_delete=models.CASCADE)
    price = models.IntegerField(default=0)
    
    class Meta:
        unique_together = (("course_request", "owner_performer"),)

class Approved_course(models.Model):
    owner_user = models.ForeignKey(Profile,related_name='owner_user',on_delete=models.CASCADE,null=True)
    owner_performer = models.ForeignKey(Profile,related_name='owner_performer',on_delete=models.SET_NULL,null=True)
    price = models.IntegerField(default=0)
    topic = models.TextField(max_length=60)
    description = models.TextField(max_length=600, default='')
    university = models.TextField(max_length=40, blank=True)
    ready = models.BooleanField(default=False)
    file = models.FileField(upload_to='uploads/',blank=True)
    
class Transactions(models.Model):
    course = models.ForeignKey(Approved_course,on_delete=models.SET_NULL,null=True)
    from_profile = models.ForeignKey(Profile,related_name='from_profile',on_delete=models.SET_NULL,null=True)
    to_profile = models.ForeignKey(Profile,related_name='to_profile', on_delete=models.SET_NULL,null=True)
    sum = models.IntegerField(default=0)
    

course_work/forms.py
from django import forms
from .models import Request_offers,Approved_course

class NewCourseForm(forms.Form):
    topic = forms.CharField(label='Тема курсовика', max_length=60)
    description = forms.CharField(label='Описание', max_length=60, widget=forms.Textarea)
    university = forms.CharField(label='Университет',max_length=40,required=False)
    teacher = forms.CharField(label='Преподаватель',max_length=40,required = False)
    min_price = forms.IntegerField(label='Минимальная предлагаемая цена')
    max_price =forms.IntegerField(label='Максимальная предлагаемая цена')
    
    def __init__(self,*args,**kwargs):
        self.user = kwargs.pop('user',None)
        super(NewCourseForm, self).__init__(*args,**kwargs)

    def is_valid(self):
        valid = super(NewCourseForm, self).is_valid()
        
        if not valid:
            return valid
        balance = self.user.profile.wallet.balance
        if balance < self.cleaned_data['max_price']:
            self.errors['Недостаточно средств']='Недостаточно средств'
            return False
        if balance < self.cleaned_data['min_price']:
            self.errors['Неверно указаны цены']='Неверно указаны цены'
            return False
        return True

        
class AcceptRequestForm(forms.Form):
    price = forms.IntegerField(label='Предлагаемая цена за курсовик')
    
    def __init__(self,*args,**kwargs):
        self.qs = kwargs.pop('qs',None)
        super(AcceptRequestForm, self).__init__(*args,**kwargs)
        
    def is_valid(self):
        valid = super(AcceptRequestForm, self).is_valid()
        if not valid:
            return valid
        if self.qs[0].min_price > self.cleaned_data['price']:
            self.errors['Цена ниже минимальной']='Цена ниже минимальной'
            return False
        if self.qs[0].max_price < self.cleaned_data['price']:
            self.errors['Цена выше максимальной']='Цена выше максимальной'
            return False
        return True

class UploadFileForm(forms.ModelForm):
    class Meta:
        model = Approved_course
        fields = ['file']

course_work/views.py
from django.views.generic.list import ListView
from django.views.generic import View
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseNotFound, HttpResponseRedirect
from .models import Course_Request,Request_offers,Approved_course,Transactions
from .forms import NewCourseForm,AcceptRequestForm,UploadFileForm
from django.shortcuts import render
from main.models import Profile
import os
from django.conf import settings
from django.http import HttpResponse




class CourseView(ListView):
    model = Course_Request
    template_name = r'course_work/templates/course.html'
   
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if context['object_list']:
            user = self.request.user
            if user.has_perm("main.customer"):
                qs = Course_Request.objects.all()
                context['object_list'] = context['object_list'].filter(owner_user=user.profile) #Если обычный пользователь показываем только его заказаные работы
            if user.has_perm("main.performer"):
                qs = Request_offers.objects.filter(owner_performer=user.profile)
                l=[]
                for q in qs:
                    l.append(q.course_request_id)
                if l:
                    context['Request_offers'] = l
        return context #Если исполнитель то возвращаем весь список
    
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if request.user.has_perm("main.reviewer"):#Рецензенту нафиг не сдаля этот список
            return HttpResponseNotFound('<h1>No Page Here</h1>')
        return super(CourseView, self).dispatch(request, *args, **kwargs)


class NewCourseView(View):
    template_name = r'course_work/templates/new_course.html'
    
    def post(self,request,*args,**kwargs):
        form = NewCourseForm(request.POST,user=request.user)
        if form.is_valid():
            topic = form.cleaned_data['topic']
            if form.cleaned_data['university']:
                university = form.cleaned_data['university']
            else:
                university=''
            if form.cleaned_data['teacher']:
                teacher = form.cleaned_data['teacher']
            else:
                teacher=''
            min_price = form.cleaned_data['min_price']
            max_price = form.cleaned_data['max_price']
            description = form.cleaned_data['description']
            c = Course_Request(
                owner_user=request.user.profile,
                topic=topic,
                description=description,
                university=university,
                teacher=teacher,
                min_price=min_price,
                max_price=max_price
            )
            c.save()
            return HttpResponseRedirect('/course')
        return render(request, self.template_name, {'form': form})
    
    def get(self,request,*args,**kwargs):
        form = NewCourseForm()
        return render(request, self.template_name, {'form': form})
            
            
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if request.user.has_perm('main.customer'):
            return super(NewCourseView, self).dispatch(request, *args, **kwargs)
        else:
            return HttpResponseNotFound('<h1>No Page Here</h1>')


class AcceptRequestView(View):
    template_name = r'course_work/templates/accept_request.html'
    
    def post(self, request, *args, **kwargs):
        pk = kwargs.pop('pk')
        qs = Course_Request.objects.filter(pk=pk)
        form = AcceptRequestForm(request.POST,qs=qs)
        if form.is_valid():
            price = form.cleaned_data['price']
            c = Request_offers(course_request=qs[0], price=int(price),owner_performer=request.user.profile)
            c.save()
            return HttpResponseRedirect('/course')
        return render(request, self.template_name, {'form': form,'qs': qs})

    def get(self,request,*args,**kwargs):
        pk = kwargs.pop('pk')
        qs = Course_Request.objects.filter(pk=pk)
        form = AcceptRequestForm()
        return render(request, self.template_name, {'form': form, 'qs': qs} )

class DeleteRequestView(View):
    def post(self,request,*args,**kwargs):
        pk = kwargs.pop('pk')
        qs = Course_Request.objects.filter(pk=pk)
        if request.user.has_perm('main.customer') and qs[0].owner_user == request.user.profile:
            qs[0].delete()
            return HttpResponseRedirect('/course')
        #TODO Возвращать сообщение об ошибке
        return HttpResponseRedirect('/course')
    
class ChooseYourPerformerView(View):
    def post(self,request,*args,**kwargs):
        try:
            pk = kwargs.pop('pk')
        except KeyError:
            return HttpResponseRedirect('/course')
        #TODO Обработать ошибки
        try:
            performer = kwargs.pop('performer_id')
        except KeyError:
            return HttpResponseRedirect('/course')
        qs = Course_Request.objects.filter(pk=pk)
        qs2 = Request_offers.objects.filter(course_request_id=pk)
        qs2 = qs2.filter(owner_performer=performer)
        p=qs2[0].price
        t=qs[0].topic
        d=qs[0].description
        u=qs[0].university
        cust = qs[0].owner_user
        owner =qs2[0].owner_performer
        c = Approved_course(owner_user=cust,
                            owner_performer=owner,
                            price=p,
                            topic =t,
                            description=d,
                            university=u,
                            ready=False,
                            file='')
        
        cust =qs[0].owner_user
        qs3 =Profile.objects.get(pk = cust.pk)
        qs3.wallet.balance-=p
        if qs3.wallet.balance < 0 :
            pass
            #TODO обработать чтобы юзер не получал отрицательный счет :C
        t = Transactions(course=c,from_profile=cust,to_profile=owner,sum=p)
        qs3.wallet.save()
        c.save()
        t.save()
        qs.delete()
        return HttpResponseRedirect('/course')
        
       
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if request.user.has_perm('main.customer'):
            return super().dispatch(request, *args, **kwargs)
        else:
            return HttpResponseNotFound('<h1>No Page Here</h1>')


class CompleteCourseView(ListView):
    model = Approved_course
    template_name = r'course_work/templates/approved_course.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if context['object_list']:
            user = self.request.user
            if user.has_perm("main.customer"):
                context['object_list'] = context['object_list'].filter(owner_user=user.profile)
            if user.has_perm("main.performer"):
                context['object_list']= context['object_list'].filter(owner_performer=user.profile)

        return context  # Если исполнитель то возвращаем весь список
    
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if request.user.has_perm("main.reviewer"):  # Рецензенту нафиг не сдаля этот список
            return HttpResponseNotFound('<h1>No Page Here</h1>')
        return super(CompleteCourseView,self).dispatch(request, *args, **kwargs)

    
def upload_file(request, pk):
    if request.method == 'POST':
        a = Approved_course.objects.get(pk=pk)
        a.ready = True
        a.save()
        form = UploadFileForm(request.POST, request.FILES,instance=a)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/complete_course')
    else:
        form = UploadFileForm()
    return render(request, 'upload.html', {'form': form,'pk':pk})


@login_required()
def download(request, path):
    file_path = os.path.join(settings.MEDIA_ROOT, path)
    if os.path.exists(file_path):
       # a = Transactions.objects.get(course_id=pk)
      #  p=Profile.objects.get(pk = a.to_profile)
       # p.wallet.balance+=a.sum
       # p.wallet.save
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="application/vnd.pdf")
            response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
            return response


class RdyCourseView(ListView):
    model = Approved_course
    template_name = r'course_work/templates/rdy_course.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if context['object_list']:
            user = self.request.user
            if user.has_perm("main.customer"):
                context['object_list'] = context['object_list'].filter(
                    owner_user=user.profile)
            if user.has_perm("main.performer"):
                context['object_list'] = context['object_list'].filter(
                    owner_performer=user.profile)
        
        return context
    
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if request.user.has_perm(
                "main.reviewer"):  # Рецензенту нафиг не сдаля этот список
            return HttpResponseNotFound('<h1>No Page Here</h1>')
        return super(RdyCourseView, self).dispatch(request, *args,
                                                        **kwargs)

course_work/templates/accept_request.html
{% extends "base.html"%}
{% block content %}

{% for post in qs %}
<h2>Минимальная цена {{post.min_price}} , максимальная цена {{post.max_price}}</h2>
<h5>
    Описание:
</h5>
<text>
    {{post.description}}
</text>
    <h2>Минимальная цена {{post.min_price}} , максимальная цена {{post.max_price}}</h2>
{% endfor %}


  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Предложить услуги</button>
  </form>
{% if form.errors %}

    {% for error in form.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
{% endblock %}

course_work/templates/approved_course.html
{% extends "base.html"%}

{% block content %}
{%if perms.main.customer %}
<h1>Ваши заказаные курсовики</h1>
{%endif%}
{%if perms.main.performer %}
<h1>Курсовики на рассмотрении</h1>
{%endif%}
<table class="table">
    <thead>
        <tr>
            <th>Тема</th>
            <th>Цена</th>
            <th>Универ</th>
            <th>
                {%if perms.main.customer %}
                Исполнитель
                {%endif%}
                {%if perms.main.performer %}
                Заказчик
                {%endif%}
            </th>
        </tr>
    </thead>
    <tbody>
{% for course_work in object_list %}
    {% if not course_work.ready %}
    <tr>
            <td>{{course_work.topic}} </td>
            <td>{{course_work.price}}</td>
            <td>{{course_work.university}}</td>
            <td>
                {%if perms.main.customer %}
                    {{course_work.owner_performer.user.username}}
                {%endif%}
                {%if perms.main.performer %}
                    {{course_work.owner_user.user.username}}
                    <td>{%if course_work.file%}
                        Вы загрузили этот курсовик
                    {% else %}

                    <form method="get" action="{% url 'upload_file' course_work.pk %}">
                    <input type = submit value="Загрузить курсовик"}>
                    </form>

                    {% endif %}</td>
                {%endif%}
            </td>

    </tr>
     {% endif %}

{% empty %}
    <li>Нет курсовиков</li>
{% endfor %}
</tbody>
</table>
{% endblock %}

course_work/templates/course.html
{% extends "base.html"%}
{%debug%}
{% block content %}
{%if perms.main.customer %}
<h1>Ваши заказаные курсовики</h1>
{%endif%}
{%if perms.main.performer %}
<h1>Курсовики на рассмотрении</h1>
{%endif%}
<table class="table">
    <thead>
        <tr>
            <th>Тема курсовой </th>
            <th>Универ</th>
            <th>Минимальная цена</th>
            <th>Максимальная цена</th>
        </tr>
    </thead>
    <tbody>
{% for course_work in object_list %}
    <tr>
            <td>{{course_work.topic}} </td>
            <td>{{course_work.university}}</td>
            <td>{{course_work.min_price}}</td>
            <td>{{course_work.max_price}}</td>
            <td>{% for i in course_work.request_offers_set.all %}
                {%if perms.main.customer %}
                {% if i.course_request_id == course_work.id %}
                    <form method="post" action="{% url 'choose_performer' course_work.pk i.owner_performer_id %}">
                    {% csrf_token %}
                    <input type = submit value={{i.owner_performer.user.username}}> Предложил {{i.price}} <br>
                    </form>
                {% endif %}
                {%endif%}
            {% endfor %}
        </td>>
            {%if perms.main.customer %}
                <td>
                <form action="{% url 'delete_request' course_work.pk %}" method ="post">
                    {% csrf_token %}
                    <input type ="submit" value="отменить заявку">
                </form>
                </td>
            {%endif%}
            {%if perms.main.performer %}
                <form method="get" action="accept/{{course_work.pk}}">
                    {% csrf_token %}
                    {%if course_work.id in Request_offers%}
                        <td>Вы приняли эту заявку</td>
                    {%else %}
                        <td><input type="submit" class="button" value ="Принять заявку"></td>
                        {% endif %}
                </form>
            {%endif%}
    </tr>

{% empty %}
    <li>У вас нет заказаных работ</li>
{% endfor %}
</tbody>
</table>
</ul>
{%if perms.main.customer %}
<a href="{% url 'new_course' %}">Заказать новый курсовик</a>
{%endif%}
{% endblock %}

course_work/templates/new_course.html
{% extends "base.html"%}

{% block content %}
  <h2>Добавить Заявку</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Добавить заявку</button>
  </form>
{% if form.errors %}

    {% for error in form.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
{% endblock %}

course_work/templates/rdy_course.html
{% extends "base.html"%}

{% block content %}
{%if perms.main.customer %}
<h1>Ваши заказаные курсовики</h1>
{%endif%}
{%if perms.main.performer %}
<h1>Курсовики на рассмотрении</h1>
{%endif%}
<table class="table">
    <thead>
        <tr>
            <th>Тема</th>
            <th>Цена</th>
            <th>Универ</th>
            <th>
                {%if perms.main.customer %}
                Исполнитель
                {%endif%}
                {%if perms.main.performer %}
                Заказчик
                {%endif%}
            </th>
        </tr>
    </thead>
    <tbody>
{% for course_work in object_list %}
    {% if  course_work.ready %}
    <tr>
            <td>{{course_work.topic}} </td>
            <td>{{course_work.price}}</td>
            <td>{{course_work.university}}</td>
            <td>
                {%if perms.main.customer %}
                    {{course_work.owner_performer.user.username}}
                    {%if course_work.file%}
                        <a href = {% url 'download' course_work.file %} >Скачать работу</a>
                    {% endif %}
                {%endif%}
                {%if perms.main.performer %}
                    {{course_work.owner_user.user.username}}
                    <td>{%if course_work.file%}
                        Вы загрузили этот курсовик
                    {% else %}

                    <form method="get" action="{% url 'upload_file' course_work.pk %}">
                    <input type = submit value="Загрузить курсовик"}>
                    </form>

                    {% endif %}</td>
                {%endif%}
            </td>

    </tr>
     {% endif %}

{% empty %}
    <li>Нет курсовиков</li>
{% endfor %}
</tbody>
</table>
{% endblock %}

course_work/templates/upload.html
{% extends "base.html"%}

{% block content %}
  <h2>Загрузить файл</h2>
  <form enctype="multipart/form-data" method="post",action="{% url 'upload_file' pk %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Загрузить</button>
  </form>
{% endblock %}